info:
  contact: {}
  description: This is the API for ManyACG
  title: ManyACG API
  version: "1"
paths:
  /v1/artwork/random:
    get:
      description: Get a random artwork
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get a random artwork
  /v1/picture/{id}:
    get:
      description: Get a picture by id
      parameters:
      - description: Picture ID
        in: path
        name: id
        required: true
        type: integer
      - description: Return picture data
        in: query
        name: data
        type: boolean
      - description: Resize width
        in: query
        name: width
        type: integer
      - description: Resize height
        in: query
        name: height
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get a picture by id
  /v1/picture/random:
    get:
      description: Get a random picture
      parameters:
      - description: Return picture data
        in: query
        name: data
        type: boolean
      - description: Resize width
        in: query
        name: width
        type: integer
      - description: Resize height
        in: query
        name: height
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get a random picture
swagger: "2.0"
